import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Plugin to inline the PDF.js worker as a string (to avoid loading from a CDN during runtime)
const inlinePdfjsWorker = {
  name: "inline-pdfjs-worker",
  setup(build) {
    build.onLoad({ filter: /pdf\.worker\.min\.mjs$/ }, async (args) => {
      const code = await fs.promises.readFile(args.path, "utf8");
      return {
        contents: `export default ${JSON.stringify(code)};`,
        loader: "js",
      };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  plugins: [inlinePdfjsWorker],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
