import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "module";
import fs from "fs";
import { fileURLToPath } from "url";
import path from "path";

const projectRoot = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const appendLicenses = {
  name: "append-licenses",
  setup(build) {
    build.onEnd(async (result) => {
      if (result.errors.length > 0) return;

      const licenses = await fs.promises.readFile(
        path.join(projectRoot, "THIRD_PARTY_LICENSES.txt"),
        "utf8",
      );
      const prefixed = licenses
        .replace(/\*\//g, "*\\/")
        .split("\n")
        .map((line) => (line ? ` * ${line}` : " *"))
        .join("\n");
      const outfile = build.initialOptions.outfile;
      const output = await fs.promises.readFile(outfile, "utf8");
      await fs.promises.writeFile(
        outfile,
        output + "\n/*!\n * THIRD-PARTY LICENSES\n *\n" + prefixed + "\n */\n",
      );
    });
  },
};

// PDF.js polyfills Response.prototype.bytes assuming Response exists, but it's
// undefined on old Electron versions, so it throws at load before the
// installer update modal can show
function guardResponsePolyfill(code) {
  const target = "typeof Response.prototype.bytes";
  if (!code.includes(target)) {
    throw new Error("PDF.js Response polyfill not found, update the patch");
  }
  return code.replaceAll(
    target,
    '(typeof Response === "undefined" ? "function" : typeof Response.prototype.bytes)',
  );
}

const patchPdfjsGlobals = {
  name: "patch-pdfjs-globals",
  setup(build) {
    build.onLoad({ filter: /legacy[\\/]build[\\/]pdf\.mjs$/ }, async (args) => {
      const code = await fs.promises.readFile(args.path, "utf8");
      return { contents: guardResponsePolyfill(code), loader: "js" };
    });
  },
};

// Plugin to inline the PDF.js worker as a string (to avoid loading from a CDN during runtime)
const inlinePdfjsWorker = {
  name: "inline-pdfjs-worker",
  setup(build) {
    build.onLoad({ filter: /pdf\.worker\.min\.mjs$/ }, async (args) => {
      const code = await fs.promises.readFile(args.path, "utf8");
      return {
        contents: `export default ${JSON.stringify(guardResponsePolyfill(code))};`,
        loader: "js",
      };
    });
  },
};

// Rename esbuild's output (main.css) to styles.css (loaded by Obsidian)
const renameStylesheet = {
  name: "rename-stylesheet",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;

      const mainCss = path.join(projectRoot, "main.css");
      if (!fs.existsSync(mainCss)) throw new Error("No main.css to rename");
      fs.renameSync(mainCss, path.join(projectRoot, "styles.css"));
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  plugins: [
    patchPdfjsGlobals,
    inlinePdfjsWorker,
    ...(prod ? [appendLicenses] : []),
    renameStylesheet,
  ],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  jsx: "automatic",
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
