packages:
  - "ocr-extractor-api"

minimumReleaseAge: 2880
blockExoticSubdeps: true
trustPolicy: no-downgrade

# https://github.com/pnpm/pnpm/issues/10622
trustPolicyExclude:
  - semver

peerDependencyRules:
  allowedVersions:
    eslint-plugin-obsidianmd>obsidian: ">=1.8.7"

allowBuilds:
  electron: true
  esbuild: true
  tesseract.js: true
